---
# Application name
application:
  name: eXperTani

# Deployment settings
deployment:
  tasks:
    - export DEPLOYPATH=/home/extaniwe/public_html/eXperTani/sistem-pakar-eXperTani
    - /bin/cp -R images $DEPLOYPATH
